service: safer-build

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1
  memorySize: 128

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  simple:
    handler: dist/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{path+}
          method: ANY
          cors: true
